### ISSUE TITLE
incorrect grunt exit status when raml2html fails

### ISSUE THREAD

**Issue by hennus** [cybertk/grunt-raml2html#9]
Hi, I noticed that when there is an error in the .raml file that grunt just reports an 'ok' status code. When grunt is part of a build process I want that build process to stop if there is a problem with the .raml file.

If you add a call 
   done(false)
at line 30 in raml2html.coffee like this:
```coffeescript
     , (error) ->
        grunt.log.error(error)
        done(false)
        next()
```
that seems to fix it.

Thanks,
Hennus Bergman

**Comment by cybertk** [comment]
Thanks, could you help send a PR?

**Comment by hennus** [comment]
Ok, I just sent you a PR.

**Comment by cybertk** [comment]
PR #10 merged
